# nome da pipeline
name: Run Basic Testes

# em que momento sera executada
on:
  pull_request: 
    branches: [master]

jobs:
  # o que vai ser feito nessa pipeline
  # só teremos um job: rodar os testes
  cypress-run:
    # maquina que sera executado
    runs-on: ubuntu-latest

    # passo a passo para rodar os testes
    steps:
      # clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      # exemplo de execucao no terminal
      - name: Instalar dependencias do projeto
        run: echo Carla
      
      # execucao e config do projeto
      - name: Run testes
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${(secrets.CYPRESS_RECORD_KEY)}